# Generated by Django 3.0.5 on 2020-10-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='education',
            field=models.TextField(),
        ),
    ]
