# Generated by Django 3.0.5 on 2020-10-03 23:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_auto_20201003_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='is_filled',
        ),
        migrations.AlterField(
            model_name='individual',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[500, 300], upload_to='images/'),
        ),
    ]
